<?php $week = $this->week; ?>
<table class="table table-hover booking-table booking-table-user">
    <?php if($this->weekNum === 0): ?>
    <thead>
        <tr>
            <th style="width: 30%"></th>
            <th style="width: 20%"><?= $this->translate('Date') ?></th>
            <th style="width: 20%"><?= $this->translate('Time') ?></th>
            <th style="width: 10%"><?= $this->translate('Total') ?></th>
            <th style="width: 10%"><?= $this->translate('Notes') ?></th>
            <th style="width: 10%"></th>
        </tr>
    </thead>
    <?php else: ?>
    <thead><tr></tr></thead>
    <?php endif; ?>
    <tbody>
        <?php foreach($week['dates'] as $key => $day): ?>
        <tr id="row-<?= $day['date']->format('d-m-Y');?>" class="day <?= $this->bookingClasses($day['date'], (isset($day['booking']))); ?>" <?= (isset($day['booking'])) ? 'data-id="' . $day['booking']->getId() . '"' : ''  ?>>
            <?php if(!isset($day['booking'])): ?>
                <?php if(!$key): ?>
                    <td style="width: 30%"><b>WEEK <?=($this->weekNum + 1)?></b> -
                        <span class="text-muted week-total"><?=$week['workedHours']?> / <?=$week['totalHours']?> </span>

                        <?php $weekBalance = $week['balance']; ?>
                        <span class="pull-right week-balance <?= ($weekBalance >= 0) ? 'balance-success' : 'balance-danger'; ?>">
                            <?= ($weekBalance >= 0) ? '+ ' : ''; ?><?= str_replace("-", "- ", $weekBalance); ?>
                        </span>
                    </td>
                <?php else: ?>
                    <td style="width: 30%"></td>
                <?php endif; ?>
                <td style="width: 20%" class="col-date"><?= $day['date']->format('l, jS'); ?></td>
                <td style="width: 20%" class="col-time"></td>
                <td style="width: 10%" class="col-total"></td>
                <td style="width: 10%" class="col-notes"></td>
                <td style="width: 10%" class="col-actions">
                    <button data-date="<?= $day['date']->format('d-m-Y');?>" class="btn btn-success btn-xs pull-right popover-book has-spinner" type="button" id="popover-book-<?= $day['date']->format('d-m-Y'); ?>">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </td>

            <?php else: ?>
                <?php if(!$key): ?>
                    <td style="width: 30%"><b>WEEK <?=($this->weekNum + 1)?></b> -
                        <span class="text-muted week-total"><?=$week['workedHours']?> / <?=$week['totalHours']?> </span>

                        <?php $weekBalance = $week['balance']; ?>
                        <span class="pull-right week-balance <?= ($weekBalance >= 0) ? 'balance-success' : 'balance-danger'; ?>">
                            <?= ($weekBalance >= 0) ? '+ ' : ''; ?><?= str_replace("-", "- ", $weekBalance); ?>
                        </span>
                    </td>
                <?php else: ?>
                    <td style="width: 30%"></td>
                <?php endif; ?>
                <td style="width: 20%" class="col-date"><?= $day['booking']->getDate()->format('l, jS') ?></td>
                <td style="width: 20%" class="col-time"><?= $day['booking']->getStartTime()->format('H:i') ?> - <?= $day['booking']->getEndTime()->format('H:i') ?></td>
                <td style="width: 10%" class="col-total"><?= $day['booking']->getTotal() ?></td>
                <td style="width: 10%" class="col-notes">
                    <?php $notes = $day['booking']->getNotes(); ?>
                    <?php if($notes): ?>
                        <span class="fx-tooltip fx-tooltip-note" data-toggle="tooltip" data-placement="top" title="<?= $notes ?>">
                            <span class="glyphicon glyphicon-comment"></span>
                        </span>
                    <?php endif; ?>
                </td>
                <td style="width: 10%" class="col-actions">
                    <div class="btn-group pull-right">
                        <button id="popover-edit-<?= $day['date']->format('d-m-Y'); ?>" class="btn btn-xs btn-default popover-edit" data-id="<?= $day['booking']->getId(); ?>" data-date="<?= $day['date']->format('d-m-Y');?>">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </button>

                    </div>
                </td>
            <?php endif; ?>
        </tr>
        <?= $this->partial('booking/edit', ['day' => $day, 'form' => $this->form]); ?>
        <?php endforeach; ?>
    </tbody>

</table>
